### ISSUE TITLE
Paseto makes Node crash?

### ISSUE THREAD

**Issue by Extarys** [sjudson/paseto.js#4] opened 2018-10-25 03:50 UTC
I'm using Node version 8.12.0 and as soon as I include Paseto.js, nodemon crashes:
`[nodemon] app crashed - waiting for file changes before starting...`

I don't know how to get more logs for you or what the issue is. I also have no way of testing on a different computer.

I removed my node_modules and reinstalled everything. The version installed is 0.1.2.

I simply add `const Paseto = require('paseto.js')` to any file.

Can someone test this also?

How can I provide more logs?

Thanks!

**Comment by sjudson** [comment] 2018-10-25 14:03
I'll take a look. In the meantime, if you do find some minimal reproduction, let me know.

**Comment by Extarys** [comment] 2018-10-25 15:07
I'm currently setting up a VM for testing. I'll keep you updated.

**Comment by Extarys** [comment] 2018-10-25 16:06
My initial tests are inconclusive and may point to human error.
I'll update once I find the issue for the sake of completeness.

**Comment by sjudson** [comment] 2018-10-28 15:56
I've been unable to reproduce this with a toy Express app run through nodemon that just generates a token on a GET request. I'm going to close the issue for the time being, but feel free to reopen it if you're able to reproduce it or get some new information.

**Closed by sjudson** 2018-10-28 15:56 UTC

**Comment by Extarys** [comment] 2018-10-28 17:31
Thanks!
It seems that the nuxt plugin I'm using is not very stable and cause the app to crash when used with paseto. I'll open an issue on the proper repo.

Thanks for your time!
