### ISSUE TITLE
Loading base64 encoded key fails

### ISSUE THREAD

**Issue by rustyconover** [sjudson/paseto.js#37] opened 2021-08-08 13:28 UTC
I'm trying to load in a base64 encoded symmetric key using this code:

``` 
   const encoderKey = new Paseto.SymmetricKey(new Paseto.V2());
    // await encoderKey.generate();
    await encoderKey.base64(encryptionKey);
    const encoder = new Paseto.V2();
```

Returns in an error:

```
   TypeError: Cannot read property '_malloc' of undefined

      at d (node_modules/libsodium-wrappers-sumo/dist/modules-sumo/libsodium-wrappers.js:1:17462)
      at new l (node_modules/libsodium-wrappers-sumo/dist/modules-sumo/libsodium-wrappers.js:1:17376)
      at Object.e.from_base64 (node_modules/libsodium-wrappers-sumo/dist/modules-sumo/libsodium-wrappers.js:1:78331)
      at Object.fromB64URLSafe (node_modules/paseto.js/lib/utils.js:288:29)
      at SymmetricKey.base64 (node_modules/paseto.js/lib/key/symmetric.js:73:28)
```

But if I call `encoderKey.generate()` before attempting to load the key everything works.

**Comment by sjudson** [comment] 2021-08-08 17:26
@rustyconover try:

```js
   const encoderKey = new Paseto.SymmetricKey(new Paseto.V2());
   await encoderKey.base64(encryptionKey);
   const encoder = encoderKey.protocol();
```

That last line doesn't work because you're generating a new protocol object, not loading the one attached to the key. If that doesn't work (especially because the error is on the `await` line) then I would guess your `encryptionKey` is not of the right type/format.

**Comment by sjudson** [comment] 2021-09-30 13:10
Going to close this for now, feel free to reopen if the issue isn't resolved and you can provide more information.

**Closed by sjudson** 2021-09-30 13:10 UTC
